// skin.js — generated by SLOT FORGE（PixiJS 版表現層參數）
// 這份檔案只影響「畫面」，不影響機率：sprite 幀數/時長、中獎特效、噴錢數量、彩帶顏色都在這裡。
// 來源：美術動畫編輯器的設定；想微調也可以直接改這支檔案，重整頁面就生效。
const Skin = {
  "renderer": "pixi",
  "pixiVersion": "8.20.1",
  "spineVersion": "4.2",
  "sourceGame": "Cascading_PayAnywhere_6x5",
  "rowOrder": "bottomUp",
  "layering": "column",
  "motionBlur": true,
  "atlas": true,
  "winFx": {
    "scale": 1.15,
    "brightness": 1.3,
    "glow": "#fe71d9"
  },
  "popFx": {
    "scale": 1.15,
    "brightness": 1.5
  },
  "timing": {
    "reelDelay": 300,
    "spin": 2000,
    "spinTurbo": 1000,
    "fillers": 18,
    "stopPause": 100,
    "landBounce": 300,
    "refill": 400,
    "explode": 400,
    "pulse": 1,
    "pop": 0.8
  },
  "symbols": {
    "1": {
      "win": "pulse",
      "spriteStub": true,
      "z": 10,
      "zActive": 150,
      "spine": {
        "skeleton": "symbol_s1.json",
        "atlas": "symbol_s1.atlas",
        "pages": {
          "symbol.png": "symbol.png"
        },
        "idle": "idle",
        "win": "win",
        "winLoop": false,
        "scale": 1.5,
        "plate": "temp.png"
      }
    },
    "2": {
      "win": "pulse",
      "spriteStub": true,
      "z": 10,
      "zActive": 150,
      "spine": {
        "skeleton": "symbol_s2.json",
        "atlas": "symbol_s2.atlas",
        "pages": {
          "symbol.png": "symbol.png"
        },
        "idle": "idle",
        "win": "win",
        "winLoop": false,
        "scale": 1.5,
        "plate": "temp.png"
      }
    },
    "3": {
      "win": "pulse",
      "spriteStub": true,
      "z": 10,
      "zActive": 150,
      "spine": {
        "skeleton": "symbol_s3.json",
        "atlas": "symbol_s3.atlas",
        "pages": {
          "symbol.png": "symbol.png"
        },
        "idle": "idle",
        "win": "win",
        "winLoop": false,
        "scale": 1.5,
        "plate": "temp.png"
      }
    },
    "4": {
      "win": "pulse",
      "spriteStub": true,
      "z": 10,
      "zActive": 150,
      "spine": {
        "skeleton": "symbol_s4.json",
        "atlas": "symbol_s4.atlas",
        "pages": {
          "symbol.png": "symbol.png"
        },
        "idle": "idle",
        "win": "win",
        "winLoop": false,
        "scale": 1.5,
        "plate": "temp.png"
      }
    },
    "5": {
      "win": "pulse",
      "spriteStub": true,
      "z": 10,
      "zActive": 150,
      "spine": {
        "skeleton": "symbol_s5.json",
        "atlas": "symbol_s5.atlas",
        "pages": {
          "symbol.png": "symbol.png"
        },
        "idle": "idle",
        "win": "win",
        "winLoop": false,
        "scale": 1.5,
        "plate": "temp.png"
      }
    },
    "6": {
      "win": "pulse",
      "z": 10,
      "zActive": 900
    },
    "7": {
      "win": "pulse",
      "z": 10,
      "zActive": 900
    },
    "8": {
      "win": "pulse",
      "z": 10,
      "zActive": 900
    },
    "9": {
      "win": "pulse",
      "z": 10,
      "zActive": 900
    },
    "10": {
      "win": "pulse",
      "z": 10,
      "zActive": 900
    },
    "11": {
      "win": "pop",
      "spriteStub": true,
      "widthScale": 1.15,
      "glow": {
        "color": "rgba(255, 215, 0, 0.8)",
        "blur": 10
      },
      "z": 200,
      "zActive": 800,
      "spine": {
        "skeleton": "symbol_scatter.json",
        "atlas": "symbol_scatter.atlas",
        "pages": {
          "symbol.png": "symbol.png"
        },
        "idle": "idle",
        "win": "win",
        "winLoop": false,
        "scale": 1.5
      }
    },
    "20": {
      "win": "pop",
      "spriteStub": true,
      "widthScale": 1.25,
      "glow": {
        "color": "rgba(0, 110, 255, 0.9)",
        "blur": 8
      },
      "z": 180,
      "zActive": 999,
      "spine": {
        "skeleton": "symbol_x2.json",
        "atlas": "symbol_x2.atlas",
        "pages": {
          "symbol.png": "symbol.png"
        },
        "idle": "idle",
        "win": "win",
        "winLoop": false,
        "scale": 1.5
      }
    },
    "21": {
      "win": "pop",
      "spriteStub": true,
      "widthScale": 1.25,
      "glow": {
        "color": "rgba(0, 110, 255, 0.9)",
        "blur": 8
      },
      "z": 180,
      "zActive": 999,
      "spine": {
        "skeleton": "symbol_x10.json",
        "atlas": "symbol_x10.atlas",
        "pages": {
          "symbol.png": "symbol.png"
        },
        "idle": "idle",
        "win": "win",
        "winLoop": false,
        "scale": 1.5
      }
    },
    "22": {
      "win": "pop",
      "spriteStub": true,
      "widthScale": 1.25,
      "glow": {
        "color": "rgba(0, 110, 255, 0.9)",
        "blur": 8
      },
      "z": 180,
      "zActive": 999,
      "spine": {
        "skeleton": "symbol_x25.json",
        "atlas": "symbol_x25.atlas",
        "pages": {
          "symbol.png": "symbol.png"
        },
        "idle": "idle",
        "win": "win",
        "winLoop": false,
        "scale": 1.5
      }
    },
    "23": {
      "win": "pop",
      "spriteStub": true,
      "widthScale": 1.25,
      "glow": {
        "color": "rgba(0, 110, 255, 0.9)",
        "blur": 8
      },
      "z": 180,
      "zActive": 999,
      "spine": {
        "skeleton": "symbol_x100.json",
        "atlas": "symbol_x100.atlas",
        "pages": {
          "symbol.png": "symbol.png"
        },
        "idle": "idle",
        "win": "win",
        "winLoop": false,
        "scale": 1.5
      }
    },
    "24": {
      "win": "pulse",
      "widthScale": 1.25,
      "glow": {
        "color": "rgba(0, 110, 255, 0.9)",
        "blur": 8
      },
      "z": 180,
      "zActive": 900
    }
  },
  "explosion": {
    "src": "explosion_sprite.png",
    "frames": 15,
    "dur": 0.5,
    "loop": false,
    "size": 2.22,
    "offsetX": -0.08
  },
  "effects": {
    "coinImg": "coin.png",
    "confettiColors": [
      "#ffd700",
      "#ff4500",
      "#00e5ff",
      "#7c4dff",
      "#27e07e"
    ],
    "confettiDurMin": 1.5,
    "confettiDurMax": 3.5,
    "tiers": {
      "big": {
        "coins": 40,
        "confetti": 50
      },
      "mid": {
        "coins": 100
      },
      "small": {
        "coins": 30
      }
    }
  }
};

export default Skin;